@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber
actor "Backoffice Operator" as BOP

participant ":AddEngineToAircraftModelUI" as UI
participant ":AddEngineToAircraftModelController" as CTRL
participant "authz\n:AuthorizationService" as AUTHZ
participant "amRepo\n:AircraftModelRepository" as AMREPO
participant "emRepo\n:EngineModelRepository" as EMREPO
participant "selectedAircraftModel\n:AircraftModel" as AM

activate BOP
BOP -> UI : asks to add an engine to an aircraft model
activate UI

UI -> CTRL** : create()
UI -> CTRL : activeAircraftModels()
activate CTRL

CTRL -> AUTHZ : ensureAuthenticatedUserHasAnyOf(RoleType.BACKOFFICE_OPERATOR)
activate AUTHZ
AUTHZ --> CTRL : (ok)
deactivate AUTHZ

CTRL -> AMREPO : findAll()
activate AMREPO
AMREPO --> CTRL : aircraftModelsList
deactivate AMREPO

CTRL --> UI : aircraftModelsList
deactivate CTRL

UI --> BOP : displays available Aircraft Models and asks to select one
deactivate UI

BOP -> UI : selects an Aircraft Model
activate UI

UI -> CTRL : availableEngineModels()
activate CTRL

CTRL -> EMREPO : findAll()
activate EMREPO
EMREPO --> CTRL : engineModelsList
deactivate EMREPO

CTRL --> UI : engineModelsList
deactivate CTRL

UI --> BOP : displays available Engine Models and asks to select one
deactivate UI

BOP -> UI : selects an Engine Model
activate UI

UI -> CTRL : addEngineToAircraftModel(selectedAircraftModel, selectedEngineModel)
activate CTRL


CTRL -> AM : addCertifiedEngine(selectedEngineModel)
activate AM

note right of AM: Validates compatibility (US057.1)\nand duplication (US057.2).

AM -> AM : certifiedEngineModels.add(selectedEngineModel.identity())
note right of AM: Stores only the Engine Name (String)\nto maintain Low Coupling\nbetween Aggregate Roots.

AM --> CTRL : (success)
deactivate AM


CTRL -> AMREPO : save(selectedAircraftModel)
activate AMREPO
note right of AMREPO: Checks @Version field.\nThrows ConcurrencyException\nif data was modified concurrently (US057.3).
AMREPO --> CTRL : updatedAircraftModel
deactivate AMREPO

CTRL --> UI : updatedAircraftModel
deactivate CTRL

UI --> BOP : displays operation success message
deactivate UI
deactivate BOP

@enduml