@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0

title US057 - Sub-Domain Model

package "AircraftModel Aggregate" <<Rectangle>> {
    class AircraftModel <<entity, aggregate root>> {
        - modelName
        - aircraftType
        - version : Long <<@Version>>
        + addEngine(engine: EngineModel)
    }
}

package "EngineModel Aggregate" <<Rectangle>> {
    class EngineModel <<entity, aggregate root>> {
        - name
        - makerName
        - engineType
    }
}


AircraftModel "1" --> "1..*" EngineModel : "certified with"

@enduml