persistence.persistenceUnit=eapli.exemplo
#persistence.repositoryFactory=eapli.exemplo.persistence.jpa.JpaRepositoryFactory
persistence.repositoryFactory=eapli.exemplo.persistence.inmemory.InMemoryRepositoryFactory
ui.menu.layout=horizontal
HighCaloriesDishLimit=300
