package aisafe.reporting.application;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;

/**
 * Builds the shared textual structure used by operational reports.
 */
public final class OperationalReportFormatter {

    private static final DateTimeFormatter MONTH_FORMAT =
            DateTimeFormatter.ofPattern("MMMM yyyy", Locale.ENGLISH);
    private static final DateTimeFormatter GENERATED_AT_FORMAT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

    public String format(final ReportData reportData) {
        if (reportData == null) {
            throw new IllegalArgumentException("Report data cannot be null.");
        }

        final StringBuilder sb = new StringBuilder();
        sb.append("==================================================\n");
        sb.append("                     AISAFE\n");
        sb.append("==================================================\n");
        sb.append("Report Type   : ").append(reportData.reportType()).append('\n');
        sb.append("Air Control   : ").append(reportData.areaCode())
                .append(" - ").append(reportData.areaName()).append('\n');
        sb.append("Period        : ").append(reportData.reportingMonth().atDay(1).format(MONTH_FORMAT)).append('\n');
        sb.append("Generated By  : ").append(reportData.generatedBy()).append('\n');
        sb.append("Generated At  : ").append(LocalDateTime.now().format(GENERATED_AT_FORMAT)).append('\n');
        sb.append("==================================================\n\n");

        for (final ReportSection section : reportData.sections()) {
            sb.append("--------------------------------------------------\n");
            sb.append(section.title()).append('\n');
            sb.append("--------------------------------------------------\n");
            for (final String line : section.lines()) {
                sb.append(line).append('\n');
            }
            sb.append('\n');
        }

        sb.append("==================================================\n");
        sb.append("End of report\n");
        sb.append("==================================================\n");
        return sb.toString();
    }
}
