@startuml aggregate-3_1
skinparam shadowing false
title Aggregate: AirTransportCompany — Register an air transport company (US060)

participant ":RegisterAirTransportCompanyUI" as UI
participant ":RegisterAirTransportCompanyController" as CTRL
participant "company:AirTransportCompany" as DOMAIN
participant ":AirTransportCompanyRepository" as REPO

activate UI
UI -> CTRL : registerCompany(name, iataCode, icaoCode)
activate CTRL
CTRL -> DOMAIN** : create(name, iataCode, icaoCode)

alt name already exists or iataCode not unique or icaoCode not unique
    DOMAIN --> CTRL : throws IllegalArgumentException
else valid
    DOMAIN --> CTRL : company
end

CTRL -> REPO : save(company)
activate REPO
REPO --> CTRL : savedCompany
deactivate REPO
CTRL --> UI : savedCompany
deactivate CTRL
UI --> : displays success message
deactivate UI

@enduml
