@startuml
autonumber

actor "Backoffice Operator" as BO
participant ":RegisterAirTransportCompanyUI" as UI <<presentation>>
participant ":RegisterAirTransportCompanyController" as Controller <<application>>
participant "company\n:AirTransportCompany" as Domain <<domain>>
participant "companyRepository\n:AirTransportCompanyRepository" as Repository <<repository>>

BO -> UI : asks to register a new air transport company
activate UI
UI --> BO : requests data (name, IATA code, ICAO code)
deactivate UI

BO -> UI : types requested data
activate UI

UI -> Controller : registerCompany(name, iata, icao)
activate Controller


Controller -> Domain : create(name, iata, icao)
activate Domain
Domain --> Controller : company
deactivate Domain

note right of Controller
  Repository creation via PersistenceContext and Factory
  was omitted in this diagram for readability purposes.
end note

Controller -> Repository : save(company)
activate Repository
Repository --> Controller : company
deactivate Repository

Controller --> UI : company
deactivate Controller

UI --> BO : displays operation success
deactivate UI

@enduml