@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0

title US063 - Sub-Domain Model

package "Collaborator Aggregate" <<Rectangle>> {
    class Collaborator <<entity, aggregate root>>
}

package "User Aggregate" <<Rectangle>> {
    class User <<entity, aggregate root>> {
        name
        phoneNumber
        position
        status
        skillsAssessmentDate
    }

    class Email <<value object>> {
        address
    }

    User "1" *-- "1" Email : "identified by"
}

package "AirTransportCompany Aggregate" <<Rectangle>> {
    class AirTransportCompany <<entity, aggregate root>> {
        name
    }
}

package "AirControlArea Aggregate" <<Rectangle>> {
    class AirControlArea <<entity, aggregate root>> {
        areaCode
        name
        minimumFuelRequired
    }
}

Collaborator "1" --> "1" User : "is a"
Collaborator "0..*" --> "0..1" AirTransportCompany : "works for"
Collaborator "0..*" --> "0..1" AirControlArea : "works for"

@enduml
