#####################################################
##
## Base
##
#####################################################

persistence.repositoryFactory=eapli.exemplo.persistence.impl.jpa.JpaRepositoryFactory
#persistence.repositoryFactory=eapli.exemplo.persistence.impl.inmemory.InMemoryRepositoryFactory
persistence.persistenceUnit=eapli.exemplo
ui.menu.layout=vertical
HighCaloriesDishLimit=300